---
- hosts: all
  become: yes
  tasks:
  - name: deploy war file from nexus
    get_url:
      url:http://100.25.180.168:8081/nexus/service/local/repositories/ram/content/java/sparkjava-hello-world/1.0.0/sparkjava-hello-world-1.0.0.war
      dest:
